[package]
name = "rfidpos-tester"
version = "0.1.0"
authors = ["Aditya Kresna <aditya.kresna@outlook.co.id>"]
edition = "2018"

[dependencies]
rfidpos-proto = { path = "../rfidpos-proto" }
crc16 = "0.4.0"
